# Generated by Django 4.2.1 on 2023-05-09 15:08

import colorfield.fields
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('name', models.CharField(max_length=25, primary_key=True, serialize=False, unique=True)),
                ('color_code', colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=18, samples=None, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ColorSetAssmt',
            fields=[
                ('name', models.CharField(max_length=200, primary_key=True, serialize=False, unique=True)),
                ('type', models.CharField(choices=[('r', 'Rubric'), ('a', 'ACJ'), ('t', 'CTJ')], default='r', max_length=1)),
                ('date_started', models.DateTimeField(auto_now_add=True)),
                ('date_ended', models.DateTimeField(blank=True, null=True)),
                ('duration', models.DurationField(blank=True, null=True)),
                ('nb_of_assmnt', models.SmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(limit_value=0)])),
                ('nb_of_assmnt_max', models.SmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(limit_value=0)])),
                ('judge', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='is_User', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ColorSet',
            fields=[
                ('name', models.CharField(max_length=25, primary_key=True, serialize=False, unique=True)),
                ('description', models.TextField(blank=True, max_length=200)),
                ('quantityOfColors', models.SmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('colors', models.ManyToManyField(to='colorTestApp.color')),
            ],
        ),
        migrations.CreateModel(
            name='ColorRubricAssmt',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('shade_guessed', models.SmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(255)])),
                ('time_start', models.DateTimeField(blank=True, null=True)),
                ('time_end', models.DateTimeField(blank=True, null=True)),
                ('duration', models.DurationField(blank=True, null=True)),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='colorTestApp.color')),
                ('color_set_assmt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='of_ColorSetAssmt', to='colorTestApp.colorsetassmt')),
            ],
        ),
    ]
