# Generated by Django 4.2.1 on 2023-05-12 12:39

import colorfield.fields
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('name', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('color_code', colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=18, samples=None, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ColorSet',
            fields=[
                ('name', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True, max_length=200)),
                ('quantity_of_colors', models.PositiveSmallIntegerField(default=0, help_text="you don't have to modify this field, it's automatically updated when saved")),
                ('colors', models.ManyToManyField(blank=True, related_name='color_sets', to='colorTestApp.color')),
            ],
        ),
        migrations.CreateModel(
            name='ColorSetAssessment',
            fields=[
                ('name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('r', 'Rubric'), ('a', 'ACJ'), ('t', 'CTJ')], default='r', max_length=1, verbose_name='Type of the test')),
                ('date_started', models.DateTimeField(auto_now_add=True, verbose_name='Start date of the test')),
                ('date_ended', models.DateTimeField(blank=True, null=True, verbose_name='End date of the test')),
                ('assessments_duration', models.DurationField(blank=True, null=True, verbose_name='Duration of assessments')),
                ('nb_of_assmnt', models.PositiveSmallIntegerField(default=0, verbose_name='Number of assessments done')),
                ('nb_of_assmnt_max', models.PositiveSmallIntegerField(default=0, verbose_name='Maximum number of assessments allowed')),
                ('color_set', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assessments', to='colorTestApp.colorset', verbose_name='Color Set')),
                ('judge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessed_color_sets', to=settings.AUTH_USER_MODEL, verbose_name='The user who assessed the color set')),
            ],
            options={
                'verbose_name_plural': 'Color Set Assessments',
            },
        ),
        migrations.CreateModel(
            name='ColorRubricAssessment',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('shade_guessed', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(255)])),
                ('time_start', models.DateTimeField(blank=True, null=True)),
                ('time_end', models.DateTimeField(blank=True, null=True)),
                ('duration', models.DurationField(blank=True, null=True)),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rubric_assessments', to='colorTestApp.color')),
                ('color_set_assmt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rubric_assessments', to='colorTestApp.colorsetassessment')),
            ],
        ),
    ]
