# Generated by Django 4.2.1 on 2023-05-10 15:14

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('colorTestApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColorRubricAssessment',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('shade_guessed', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(255)])),
                ('time_start', models.DateTimeField(blank=True, null=True)),
                ('time_end', models.DateTimeField(blank=True, null=True)),
                ('duration', models.DurationField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ColorSetAssessment',
            fields=[
                ('name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('r', 'Rubric'), ('a', 'ACJ'), ('t', 'CTJ')], default='r', max_length=1, verbose_name='Type of the test')),
                ('date_started', models.DateTimeField(auto_now_add=True, verbose_name='Start date of the test')),
                ('date_ended', models.DateTimeField(blank=True, null=True, verbose_name='End date of the test')),
                ('assessments_duration', models.DurationField(blank=True, null=True, verbose_name='Duration of assessments')),
                ('nb_of_assmnt', models.PositiveSmallIntegerField(default=0, verbose_name='Number of assessments done')),
                ('nb_of_assmnt_max', models.PositiveSmallIntegerField(default=0, verbose_name='Maximum number of assessments allowed')),
                ('judge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessed_color_sets', to=settings.AUTH_USER_MODEL, verbose_name='The user who assessed the color set')),
            ],
            options={
                'verbose_name_plural': 'Color Set Assessments',
            },
        ),
        migrations.RemoveField(
            model_name='colorsetassmt',
            name='judge',
        ),
        migrations.RemoveField(
            model_name='colorset',
            name='quantityOfColors',
        ),
        migrations.AddField(
            model_name='colorset',
            name='quantity_of_colors',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='color',
            name='name',
            field=models.CharField(max_length=25, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='colorset',
            name='colors',
            field=models.ManyToManyField(blank=True, related_name='color_sets', to='colorTestApp.color'),
        ),
        migrations.AlterField(
            model_name='colorset',
            name='name',
            field=models.CharField(max_length=25, primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='ColorRubricAssmt',
        ),
        migrations.DeleteModel(
            name='ColorSetAssmt',
        ),
        migrations.AddField(
            model_name='colorrubricassessment',
            name='color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rubric_assessments', to='colorTestApp.color'),
        ),
        migrations.AddField(
            model_name='colorrubricassessment',
            name='color_set_assmt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rubric_assessments', to='colorTestApp.colorsetassessment'),
        ),
    ]
