# Generated by Django 4.2.1 on 2023-05-12 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('colorTestApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='colorset',
            name='quantity_of_colors',
        ),
    ]
