# Generated by Django 4.2.1 on 2023-05-12 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('colorTestApp', '0002_remove_colorset_quantity_of_colors'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='colorrubricassessment',
            options={'verbose_name_plural': 'Color Rubric Assessment'},
        ),
    ]
