# Generated by Django 4.2.1 on 2023-05-15 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colorTestApp', '0003_alter_colorrubricassessment_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colorsetassessment',
            name='date_started',
            field=models.DateTimeField(verbose_name='Start date of the test'),
        ),
    ]
