# Generated by Django 4.2.1 on 2023-05-18 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colorTestApp', '0004_alter_colorsetassessment_date_started'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='colorrubricassessment',
            options={'get_latest_by': 'time_start', 'verbose_name_plural': 'Color Rubric Assessment'},
        ),
        migrations.AlterModelOptions(
            name='colorsetassessment',
            options={'get_latest_by': 'date_started', 'ordering': ['date_started', 'judge'], 'verbose_name_plural': 'Color Set Assessments'},
        ),
        migrations.AlterField(
            model_name='colorsetassessment',
            name='nb_of_assmnt_max',
            field=models.PositiveSmallIntegerField(default=5, verbose_name='Maximum number of assessments allowed'),
        ),
    ]
