# Generated by Django 4.2.1 on 2023-05-18 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('colorTestApp', '0005_alter_colorrubricassessment_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='colorsetassessment',
            options={'get_latest_by': 'date_started', 'ordering': ['date_started'], 'verbose_name_plural': 'Color Set Assessments'},
        ),
        migrations.RenameField(
            model_name='colorrubricassessment',
            old_name='color_set_assmt',
            new_name='color_set_assessment',
        ),
    ]
