# Generated by Django 4.2.1 on 2023-05-22 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colorTestApp', '0007_alter_colorsetassessment_date_started'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colorsetassessment',
            name='date_started',
            field=models.DateTimeField(verbose_name='Start date of the test'),
        ),
    ]
