# Generated by Django 4.2.1 on 2023-05-22 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('colorTestApp', '0008_alter_colorsetassessment_date_started'),
    ]

    operations = [
        migrations.RenameField(
            model_name='colorsetassessment',
            old_name='nb_of_assmnt',
            new_name='nb_of_assessement',
        ),
        migrations.RenameField(
            model_name='colorsetassessment',
            old_name='nb_of_assmnt_max',
            new_name='nb_of_assessement_max',
        ),
    ]
