# Generated by Django 4.2.1 on 2023-08-02 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('colorTestApp', '0009_rename_nb_of_assmnt_colorsetassessment_nb_of_assessement_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColorAcjAssessment',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('estimated_values', models.JSONField(blank=True, null=True)),
                ('comparisons', models.JSONField(blank=True, null=True)),
                ('time_start', models.DateTimeField(blank=True, null=True)),
                ('time_end', models.DateTimeField(blank=True, null=True)),
                ('duration', models.DurationField(blank=True, null=True)),
                ('color_A', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='color_a_of_acj_assessment', to='colorTestApp.color')),
                ('color_B', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='color_b_of_acj_assessment', to='colorTestApp.color')),
                ('color_selected', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='acj_assessments', to='colorTestApp.color')),
                ('color_set_assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acj_assessments', to='colorTestApp.colorsetassessment')),
            ],
            options={
                'verbose_name_plural': 'Color Acj Assessment',
                'get_latest_by': 'time_start',
            },
        ),
    ]
