# Generated by Django 4.2.1 on 2023-08-03 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('colorTestApp', '0010_coloracjassessment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coloracjassessment',
            old_name='comparisons',
            new_name='acj_data',
        ),
        migrations.RemoveField(
            model_name='coloracjassessment',
            name='estimated_values',
        ),
    ]
